export { default as OP } from './OP'
export { default as Script } from './Script'
export { default as LockingScript } from './LockingScript'
export { default as UnlockingScript } from './UnlockingScript'
export { default as Spend } from './Spend'
export type { default as ScriptTemplate } from './ScriptTemplate'
export * from './templates/index'
